import {
  createHmac,
  randomBytes,
  scryptSync,
  timingSafeEqual,
} from "node:crypto";
import fs from "node:fs";
import path from "node:path";

/**
 * Stateless, signed admin sessions.
 *
 * Kept free of any `next/*` imports so both the request Proxy and Server
 * Components/Actions can use it. Cookie handling lives in `lib/auth.ts`.
 *
 * Nothing here ever reaches the browser: credentials come from environment
 * variables and the cookie only carries a signed username + expiry.
 */

export const SESSION_COOKIE = "markui_admin_session";
export const SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 7; // 7 days

export interface SessionPayload {
  /** Username of the signed-in admin. */
  u: string;
  /** Issued-at, epoch seconds. */
  iat: number;
  /** Expiry, epoch seconds. */
  exp: number;
}

// ─── Secret ──────────────────────────────────────────────────────────────────

let cachedSecret: string | null = null;

/**
 * Prefers `ADMIN_SESSION_SECRET`. In development only, falls back to a random
 * secret persisted under `.data` so sessions survive a dev-server restart even
 * when `.env.local` has not been created yet.
 */
function getSecret(): string {
  if (cachedSecret) return cachedSecret;

  const fromEnv = process.env.ADMIN_SESSION_SECRET;
  if (fromEnv && fromEnv.length >= 16) {
    cachedSecret = fromEnv;
    return cachedSecret;
  }

  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "ADMIN_SESSION_SECRET is not set. Generate one with `npm run admin:setup`.",
    );
  }

  const devSecretFile = path.join(process.cwd(), ".data", "dev-session-secret");
  try {
    cachedSecret = fs.readFileSync(devSecretFile, "utf8").trim();
    if (cachedSecret.length >= 16) return cachedSecret;
  } catch {
    // Falls through to generating one.
  }

  cachedSecret = randomBytes(32).toString("base64url");
  try {
    fs.mkdirSync(path.dirname(devSecretFile), { recursive: true });
    fs.writeFileSync(devSecretFile, cachedSecret, "utf8");
  } catch {
    // In-memory only; sessions reset on restart.
  }
  return cachedSecret;
}

// ─── Passwords ───────────────────────────────────────────────────────────────

const SCRYPT_KEYLEN = 64;

/**
 * Produces the `scrypt:<saltHex>:<hashHex>` string stored in the environment.
 *
 * The separator is `:` rather than the more conventional `$` because Next's
 * dotenv loader expands `$...` sequences, which would silently truncate the
 * hash to `scrypt` and make every login fail.
 */
export function hashPassword(password: string, salt?: string): string {
  const s = salt ?? randomBytes(16).toString("hex");
  const hash = scryptSync(password, s, SCRYPT_KEYLEN).toString("hex");
  return `scrypt:${s}:${hash}`;
}

function safeEqual(a: string, b: string) {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}

export function verifyPassword(password: string, stored: string): boolean {
  // `$` is also accepted so a hash generated by another tool still works.
  const parts = stored.split(stored.includes(":") ? ":" : "$");
  if (parts.length !== 3 || parts[0] !== "scrypt") return false;
  try {
    const [, salt] = parts;
    const expected = scryptSync(password, salt, SCRYPT_KEYLEN).toString("hex");
    return safeEqual(expected, parts[2]);
  } catch {
    return false;
  }
}

/**
 * Checks a submitted username/password against the configured admin account.
 * `ADMIN_PASSWORD_HASH` is preferred; `ADMIN_PASSWORD` is a plain-text
 * convenience for local development only.
 */
export function verifyCredentials(username: string, password: string): boolean {
  const expectedUser = process.env.ADMIN_USERNAME || "admin";
  const hash = process.env.ADMIN_PASSWORD_HASH;
  const plain = process.env.ADMIN_PASSWORD;

  // Always run both comparisons so a wrong username is not faster than a
  // wrong password.
  const userOk = safeEqual(username, expectedUser);
  let passOk = false;

  if (hash) {
    passOk = verifyPassword(password, hash);
  } else if (plain) {
    passOk = safeEqual(password, plain);
  } else if (process.env.NODE_ENV !== "production") {
    // No credentials configured at all: allow the documented dev default so a
    // fresh clone can still reach the dashboard.
    passOk = safeEqual(password, "admin");
  }

  return userOk && passOk;
}

/** True when the deployment has no admin credentials configured. */
export function hasConfiguredCredentials(): boolean {
  return Boolean(process.env.ADMIN_PASSWORD_HASH || process.env.ADMIN_PASSWORD);
}

// ─── Session tokens ──────────────────────────────────────────────────────────

function sign(data: string): string {
  return createHmac("sha256", getSecret()).update(data).digest("base64url");
}

export function createToken(username: string): string {
  const now = Math.floor(Date.now() / 1000);
  const payload: SessionPayload = {
    u: username,
    iat: now,
    exp: now + SESSION_MAX_AGE_SECONDS,
  };
  const body = Buffer.from(JSON.stringify(payload)).toString("base64url");
  return `${body}.${sign(body)}`;
}

/** Returns the payload when the signature is valid and unexpired, else `null`. */
export function verifyToken(token: string | undefined): SessionPayload | null {
  if (!token) return null;

  const dot = token.lastIndexOf(".");
  if (dot <= 0) return null;

  const body = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  if (!safeEqual(signature, sign(body))) return null;

  try {
    const payload = JSON.parse(
      Buffer.from(body, "base64url").toString("utf8"),
    ) as SessionPayload;

    if (typeof payload.u !== "string" || typeof payload.exp !== "number") {
      return null;
    }
    if (payload.exp <= Math.floor(Date.now() / 1000)) return null;

    return payload;
  } catch {
    return null;
  }
}
